Readme update
th2-net/th2-infra pull request #254
Opened 2022-07-22 19:02 UTC by sabamushtashvili

2022-07-26 10:13 UTC, Andrei-Shulika requested changes
@sabamushtashvili 
Need to change this section. Private key is required at installation.
This comment need to be deleted according to comment above.
`# required if http(s) access to gitlab/github repositories is used`

2022-07-26 14:49 UTC, bop0hz commented
We also must update comments in values.yaml to more meaningful and compliant to doc generator

2022-08-03 07:29 UTC, bop0hz commented on chart/templates/configs/secret-infra-mgr.yaml
> +    app.kubernetes.io/managed-by: "Helm"
must not contain helm labels and annotations

2022-08-03 07:29 UTC, bop0hz commented on chart/templates/configs/secret-infra-mgr.yaml
> +  name: {{ .Values.infraMgr.git.secretName }}
do not set value for name, just hardcode it

2022-08-03 07:29 UTC, bop0hz commented on chart/tests/secret-infra-mgr_test.yaml
> +          privateKey: "key"
where is repository value?

2022-08-03 07:29 UTC, bop0hz commented on README.md
> +# git:
please add one space character

2022-08-04 10:21 UTC, bop0hz commented on chart/tests/secret-infra-mgr_test.yaml
> +          value: infra-mgr
redundant

2022-08-10 10:58 UTC, bop0hz approved these changes

2022-08-10 10:59 UTC, merged