annotations
th2-net/th2-infra pull request #83
Opened 2022-02-10 07:48 UTC by Maximus905

2022-02-15 07:54 UTC, bop0hz commented on th2-service/templates/_infra-mgr-service.yaml
> +  {{- include "common-annotaitions" . | nindent 4  }}
typos everywhere annotaitions

2022-02-15 07:57 UTC, bop0hz commented on th2-service/templates/ingress.yaml
>    rules:
remove rabbitmq path

2022-02-15 07:57 UTC, bop0hz requested changes
please fix

2022-02-15 12:08 UTC, Maximus905 commented on th2-service/templates/_infra-mgr-service.yaml
> +  {{- include "common-annotaitions" . | nindent 4  }}
fixed

2022-02-15 12:08 UTC, Maximus905 commented on th2-service/templates/ingress.yaml
>    rules:
rabbitmq path was moved into rabbit values

2022-02-16 16:09 UTC, bop0hz commented on th2-service/values.yaml
> +      # name: infra-operator-tpl
fix before merge

2022-02-17 10:48 UTC, bop0hz approved these changes

2022-02-17 10:51 UTC, merged